logging:
  level:
    root:
      info
    com.ts.judge.provider.dao.mapper: debug
  file: /data/judge/log/provider.log
spring:
  application:
    name: judge-provider
  redis:
    host: 192.168.40.151
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.addr}
        namespace: ${nacos.namespace}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Dev@123456
    username: dev
    url: jdbc:mysql://192.168.40.147:3306/judge?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  jackson:
    default-property-inclusion: non_null

mybatis:
  type-aliases-package: com.ts.judge.provider.dao.entity
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/**/*.xml
server:
  port: 8081

com:
  ps:
    judge:
      provider:
        cron-callback-tenant: 0 0/5 * * * ?
        cron-reapply-jury: 0 0/30 * * * ?
        cron-audit-variable: 0 0/30 * * * ?
        cron-var-result-query: 0 0/30 * * * ?
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000

feign:
  hystrix:
    enabled: true

#ribbon的超时时间
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

clerk-common:
  enabled: true