
logging:
  level:
    root:
      info
  file: /data/judge/log/provider.log
spring:
  application:
    name: judge-provider
  rabbitmq:
    host: localhost
#    username: admin
#    password: admin
  redis:
    host: 192.168.40.151
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: ${CONFIG_SERVER:192.168.40.150:8848}
        #namespace: 70b438a3-b902-4247-b670-fabebe33db71
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Dev@123456
    username: dev
    url: jdbc:mysql://192.168.40.147:3306/judge?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  jackson:
    default-property-inclusion: non_null

mybatis:
  type-aliases-package: com.ps.judge.dao.entity
server:
  port: 8081

com:
  ps:
    judge:
      provider:
        cron-callback-tenant: 0 0/30 * * * ?
        cron-reapply-jury: 0 0/30 * * * ?
        cron-audit-variable: 0 0/30 * * * ?
        cron-var-result-query: 0 0/30 * * * ?
