
logging:
  level:
    root:
      info
  file: /data/judge/log/provider.log
spring:
  application:
    name: judge-provider
  rabbitmq:
    host: localhost
#    username: admin
#    password: admin
  redis:
    host: 192.168.40.151
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: ${CONFIG_SERVER:192.168.40.152:8848}
        namespace: 5c63ac8a-028b-472e-877c-fb657649a356
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.40.152:3306/judge?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: fas
    password: Fas@123456
  jackson:
    default-property-inclusion: non_null

mybatis:
  type-aliases-package: com.ps.judge.dao.entity
server:
  port: 8081

com:
  ps:
    judge:
      provider:
        cron-callback-tenant: 0 0/5 * * * ?
        cron-reapply-jury: 0 0/1 * * * ?
        cron-audit-variable: 0 0/1 * * * ?
        cron-var-result-query: 0 0/1 * * * ?
