package com.ps.judge.dao.entity;

import java.util.ArrayList;
/**
 * This class was automatically generated by the data modeler tool.
 */

public class AuditTaskTriggeredRuleDO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer id;
	private java.lang.String tenantCode;
	private java.lang.Integer taskId;
	private java.lang.String applyId;
	private java.lang.String flowCode;
	private java.lang.String rulePackageCode;
	private java.lang.String rulePackageName;
	private java.lang.String rulePackageVersion;
	private java.lang.String ruleCode;
	private java.lang.String ruleName;
	private java.lang.String ruleVersion;
	private java.lang.String expression;
	private java.lang.String param;
	private java.lang.String condition;

	private java.lang.String result;

	public AuditTaskTriggeredRuleDO() {
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getTenantCode() {
		return this.tenantCode;
	}

	public void setTenantCode(java.lang.String tenantCode) {
		this.tenantCode = tenantCode;
	}

	public java.lang.Integer getTaskId() {
		return this.taskId;
	}

	public void setTaskId(java.lang.Integer taskId) {
		this.taskId = taskId;
	}

	public java.lang.String getApplyId() {
		return this.applyId;
	}

	public void setApplyId(java.lang.String applyId) {
		this.applyId = applyId;
	}

	public java.lang.String getFlowCode() {
		return this.flowCode;
	}

	public void setFlowCode(java.lang.String flowCode) {
		this.flowCode = flowCode;
	}

	public java.lang.String getRulePackageCode() {
		return this.rulePackageCode;
	}

	public void setRulePackageCode(java.lang.String rulePackageCode) {
		this.rulePackageCode = rulePackageCode;
	}

	public java.lang.String getRulePackageName() {
		return this.rulePackageName;
	}

	public void setRulePackageName(java.lang.String rulePackageName) {
		this.rulePackageName = rulePackageName;
	}

	public java.lang.String getRulePackageVersion() {
		return this.rulePackageVersion;
	}

	public void setRulePackageVersion(java.lang.String rulePackageVersion) {
		this.rulePackageVersion = rulePackageVersion;
	}

	public java.lang.String getRuleCode() {
		return this.ruleCode;
	}

	public void setRuleCode(java.lang.String ruleCode) {
		this.ruleCode = ruleCode;
	}

	public java.lang.String getRuleName() {
		return this.ruleName;
	}

	public void setRuleName(java.lang.String ruleName) {
		this.ruleName = ruleName;
	}

	public java.lang.String getRuleVersion() {
		return this.ruleVersion;
	}

	public void setRuleVersion(java.lang.String ruleVersion) {
		this.ruleVersion = ruleVersion;
	}

	public java.lang.String getExpression() {
		return this.expression;
	}

	public void setExpression(java.lang.String expression) {
		this.expression = expression;
	}

	public java.lang.String getParam() {
		return this.param;
	}

	public void setParam(java.lang.String param) {
		this.param = param;
	}

	public java.lang.String getCondition() {
		return this.condition;
	}

	public void setCondition(java.lang.String condition) {
		this.condition = condition;
	}

	public java.lang.String getResult() {
		return this.result;
	}

	public void setResult(java.lang.String result) {
		this.result = result;
	}

	public AuditTaskTriggeredRuleDO(java.lang.Integer id,
			java.lang.String tenantCode, java.lang.Integer taskId,
			java.lang.String applyId, java.lang.String flowCode,
			java.lang.String rulePackageCode, java.lang.String rulePackageName,
			java.lang.String rulePackageVersion, java.lang.String ruleCode,
			java.lang.String ruleName, java.lang.String ruleVersion,
			java.lang.String expression, java.lang.String param,
			java.lang.String condition, java.lang.String result) {
		this.id = id;
		this.tenantCode = tenantCode;
		this.taskId = taskId;
		this.applyId = applyId;
		this.flowCode = flowCode;
		this.rulePackageCode = rulePackageCode;
		this.rulePackageName = rulePackageName;
		this.rulePackageVersion = rulePackageVersion;
		this.ruleCode = ruleCode;
		this.ruleName = ruleName;
		this.ruleVersion = ruleVersion;
		this.expression = expression;
		this.param = param;
		this.condition = condition;
		this.result = result;
	}
	
	
	public AuditTaskTriggeredRuleDO(String version,
			String rulePackageCode, String ruleCode, String expression,
			String condition, String result) {
		this.rulePackageCode = rulePackageCode;
		this.rulePackageName = "";
		this.rulePackageVersion = version;
		this.ruleCode = ruleCode;
		this.ruleName = "";
		this.ruleVersion = version;
		this.expression = expression;
		this.param = "";
		this.condition = condition;
		this.result = result;
	}
	
}