package com.ps.judge.provider.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ScoreCardVO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int score;
	private String quota;

	public ScoreCardVO() {
	}

	public int getScore() {
		return this.score;
	}

	public void setScore(int score) {
		this.score = score;
	}

	public String getQuota() {
		return this.quota;
	}

	public void setQuota(String quota) {
		this.quota = quota;
	}

	public ScoreCardVO(int score, String quota) {
		this.score = score;
		this.quota = quota;
	}

}