
spring:
  application:
    name: judge-web
  redis:
    host: 192.168.40.151
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: ${CONFIG_SERVER:192.168.40.150:8848}
    alicloud:
      access-key: LTAI4Ftbiuu38HBpvMeikex1
      secret-key: CjNZQLbZuoKdsTkfg4sS0RefKOXm3V
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
  datasource:
    url: jdbc:mysql://192.168.40.147:3306/judge?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: dev
    password: Dev@123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null

server:
  port: 8082

com:
  ps:
    judge:
      web:
          bucket-name: factoryfilestore
          base-url: http://${com.ps.judge.web.bucket-name}.oss-cn-hangzhou.aliyuncs.com/
          expiration: 31104000000  #60*60*24*30*12*1000
encrypt:
  key-store:
    location: xc.keystore
    alias: ps
    password: admin123
    secret: admin123
    type: jks
  key: 12345