package com.ps.judge.dao.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AuditTaskTriggeredRuleDO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private Integer id;
	private String tenantCode;
	private Integer taskId;
	private String applyId;
	private String flowCode;
	private String rulePackageCode;
	private String rulePackageName;
	private String rulePackageVersion;
	private String ruleCode;
	private String ruleName;
	private String ruleVersion;
	private String expression;
	private String param;
	private String condition;
	private Integer score;
	private String result;

	public AuditTaskTriggeredRuleDO() {
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTenantCode() {
		return this.tenantCode;
	}

	public void setTenantCode(String tenantCode) {
		this.tenantCode = tenantCode;
	}

	public Integer getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	public String getApplyId() {
		return this.applyId;
	}

	public void setApplyId(String applyId) {
		this.applyId = applyId;
	}

	public String getFlowCode() {
		return this.flowCode;
	}

	public void setFlowCode(String flowCode) {
		this.flowCode = flowCode;
	}

	public String getRulePackageCode() {
		return this.rulePackageCode;
	}

	public void setRulePackageCode(String rulePackageCode) {
		this.rulePackageCode = rulePackageCode;
	}

	public String getRulePackageName() {
		return this.rulePackageName;
	}

	public void setRulePackageName(String rulePackageName) {
		this.rulePackageName = rulePackageName;
	}

	public String getRulePackageVersion() {
		return this.rulePackageVersion;
	}

	public void setRulePackageVersion(String rulePackageVersion) {
		this.rulePackageVersion = rulePackageVersion;
	}

	public String getRuleCode() {
		return this.ruleCode;
	}

	public void setRuleCode(String ruleCode) {
		this.ruleCode = ruleCode;
	}

	public String getRuleName() {
		return this.ruleName;
	}

	public void setRuleName(String ruleName) {
		this.ruleName = ruleName;
	}

	public String getRuleVersion() {
		return this.ruleVersion;
	}

	public void setRuleVersion(String ruleVersion) {
		this.ruleVersion = ruleVersion;
	}

	public String getExpression() {
		return this.expression;
	}

	public void setExpression(String expression) {
		this.expression = expression;
	}

	public String getParam() {
		return this.param;
	}

	public void setParam(String param) {
		this.param = param;
	}

	public String getCondition() {
		return this.condition;
	}

	public void setCondition(String condition) {
		this.condition = condition;
	}

	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	public AuditTaskTriggeredRuleDO(Integer id,
			String tenantCode, Integer taskId,
			String applyId, String flowCode,
			String rulePackageCode, String rulePackageName,
			String rulePackageVersion, String ruleCode,
			String ruleName, String ruleVersion,
			String expression, String param,
			String condition, String result) {
		this.id = id;
		this.tenantCode = tenantCode;
		this.taskId = taskId;
		this.applyId = applyId;
		this.flowCode = flowCode;
		this.rulePackageCode = rulePackageCode;
		this.rulePackageName = rulePackageName;
		this.rulePackageVersion = rulePackageVersion;
		this.ruleCode = ruleCode;
		this.ruleName = ruleName;
		this.ruleVersion = ruleVersion;
		this.expression = expression;
		this.param = param;
		this.condition = condition;
		this.result = result;
	}
	
	
	public AuditTaskTriggeredRuleDO(String version,
			String rulePackageCode, String ruleCode, String expression,
			String condition, String result) {
		this.rulePackageCode = rulePackageCode;
		this.rulePackageName = "";
		this.rulePackageVersion = version;
		this.ruleCode = ruleCode;
		this.ruleName = "";
		this.ruleVersion = version;
		this.expression = expression;
		this.param = "";
		this.condition = condition;
		this.result = result;
	}
	
}